<script setup>
import { ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue';
import { LayoutDashboard, UserRound, Utensils, BookOpen, ChartNoAxesCombined, Database, Plus, Check, Printer, Download, ArrowUpRight, Search, X, ChevronRight, Save, Trash2, Copy, Menu, CircleAlert, LoaderCircle } from 'lucide-vue-next';
import { api } from './api';
import nutriaLogo from '../images/nutria-logo.png';
import { createFoodSearch } from './foodSearch';
import { nutrients, format, label, total, profile, consumedQuantity } from './nutrition';
import FoodPicker from './components/FoodPicker.vue';
import MealCard from './components/MealCard.vue';
import PatientsPage from './components/PatientsPage.vue';
import PortionInput from './components/PortionInput.vue';
const nav=[{id:'patients',name:'Pacientes',icon:UserRound},{id:'plan',name:'Plano alimentar',icon:LayoutDashboard},{id:'profile',name:'Avaliação',icon:UserRound},{id:'foods',name:'Alimentos',icon:Utensils},{id:'recipes',name:'Receitas',icon:BookOpen},{id:'report',name:'Análise nutricional',icon:ChartNoAxesCombined},{id:'sources',name:'Fontes de dados',icon:Database}];
const clone=value=>JSON.parse(JSON.stringify(value));
const reload=()=>window.location.reload();
const sidebar=ref(null),menuToggle=ref(null);
function closeMenuOutside(event){if(mobileNav.value&&!sidebar.value?.contains(event.target)&&!menuToggle.value?.contains(event.target))mobileNav.value=false;}
function closeMenuOnEscape(event){if(event.key==='Escape')mobileNav.value=false;}
onMounted(()=>{document.addEventListener('pointerdown',closeMenuOutside);document.addEventListener('keydown',closeMenuOnEscape);});
onUnmounted(()=>{document.removeEventListener('pointerdown',closeMenuOutside);document.removeEventListener('keydown',closeMenuOnEscape);});
const page=ref('plan'),mobileNav=ref(false),loading=ref(true),error=ref(''),notice=ref(''),busy=ref(false);
const db=ref({foods:[],plans:[],recipes:[],sources:[],patients:[],activities:[],meal_types:[],categories:[]});
const plan=ref(null),saved=ref(''),dialog=ref(null),modal=ref(null),pickerTarget=ref(null),foodDraft=ref(null);
const search=ref(''),foodCategory=ref(''),foodSource=ref(''),foodPage=ref(1),chartMetric=ref('calories');
const recipe=ref({name:'',ingredients:[],instructions:''});
const map=computed(()=>new Map(db.value.foods.map(f=>[f.id,f])));
const calculation=computed(()=>plan.value?profile(plan.value.data.profile,db.value.activities):null);
const allItems=computed(()=>plan.value?.data.meals.flatMap(m=>m.items)||[]);
const summary=computed(()=>total(allItems.value,map.value));
const recipeSummary=computed(()=>total(recipe.value.ingredients,map.value));
const dirty=computed(()=>plan.value&&JSON.stringify(plan.value)!==saved.value);
const pct=computed(()=>calculation.value?.target>0&&!summary.value.missing.calories?summary.value.totals.calories/calculation.value.target*100:null);
const matchesFoodSearch=computed(()=>createFoodSearch(search.value));
const filteredFoods=computed(()=>db.value.foods.filter(f=>matchesFoodSearch.value(f.name)&&(!foodCategory.value||f.category===foodCategory.value)&&(!foodSource.value||String(f.source_id||'custom')===foodSource.value)));
const foodPages=computed(()=>Math.max(1,Math.ceil(filteredFoods.value.length/25)));
const grouped=computed(()=>{
  const groups=new Map(); for(const i of allItems.value){const name=map.value.get(i.food_id)?.category||'Outros';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(i);}
  return [...groups].map(([name,items])=>({name,count:items.length,...total(items,map.value)}));
});
const macroEnergy=computed(()=>[summary.value.totals.protein*4,summary.value.totals.carbs*4,summary.value.totals.fat*9]);
const macroPercent=computed(()=>{const sum=macroEnergy.value.reduce((a,b)=>a+b,0);return macroEnergy.value.map(n=>sum?n/sum*100:0);});
const donut=computed(()=>{const [p,c]=macroPercent.value;return macroEnergy.value.some(v=>v>0)?`conic-gradient(#285d49 0% ${p}%, #c49a3b ${p}% ${p+c}%, #9181a8 ${p+c}% 100%)`:'#e5e9e4';});
watch([search,foodCategory,foodSource],()=>foodPage.value=1);
watch(modal,async v=>{await nextTick();if(v&&!dialog.value.open)dialog.value.showModal();if(!v&&dialog.value?.open)dialog.value.close();});
watch(page,()=>{mobileNav.value=false; window.scrollTo({top:0,behavior:'smooth'});});
window.addEventListener('beforeunload',e=>{if(dirty.value){e.preventDefault();e.returnValue='';}});
function toast(text){notice.value=text;setTimeout(()=>notice.value='',5000);}
async function perform(fn){error.value='';busy.value=true;try{await fn();}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function refresh(){db.value=await api('bootstrap');}
function selectPlan(id){if(dirty.value&&!confirm('Descartar as alterações não salvas deste plano?'))return;const p=db.value.plans.find(p=>p.id===Number(id));if(p){plan.value=clone(p);plan.value.name=plan.value.data.profile.name;saved.value=JSON.stringify(plan.value);}}
async function logout(){const result=await api('auth/logout','POST');location.assign(result.redirect);}
function patientPlan(patient){if(newPlan()===false)return;plan.value.patient_id=patient.id;plan.value.data.profile.name=patient.name;}
function selectPatient(){const patient=db.value.patients.find(p=>p.id===plan.value.patient_id);if(patient)plan.value.data.profile.name=patient.name;}
function newPlan(copy=false){if(dirty.value&&!confirm('Descartar as alterações não salvas para criar outro plano?'))return false;const p=clone(copy?plan.value:db.value.template);delete p.id;delete p.created_at;delete p.updated_at;p.version=1;p.name=p.data.profile.name;if(!copy){p.patient_id=null;p.data.profile.name='';p.data.meals.forEach(m=>m.items=[]);p.data.notes='';}plan.value=p;saved.value='';page.value='profile';return true;}
async function savePlan(){await perform(async()=>{plan.value.name=plan.value.data.profile.name;const p=await api('plans'+(plan.value.id?'/'+plan.value.id:''),plan.value.id?'PUT':'POST',plan.value);plan.value=p;saved.value=JSON.stringify(p);await refresh();if(page.value==='profile')page.value='plan';toast('Plano salvo no banco de dados.');});}
async function removePlan(){if(!plan.value.id)return;if(!confirm(`Excluir o plano “${plan.value.name}”?`))return;await perform(async()=>{await api('plans/'+plan.value.id,'DELETE');await refresh();saved.value=JSON.stringify(plan.value);if(db.value.plans.length)selectPlan(db.value.plans[0].id);else newPlan();toast('Plano excluído.');});}
function openPicker(target){pickerTarget.value=target;modal.value='picker';}
function addFood(item){if(pickerTarget.value==='recipe')recipe.value.ingredients.push(item);else plan.value.data.meals[pickerTarget.value].items.push({...item,multiplier:1});modal.value=null;toast('Alimento adicionado.');}
function newFood(f){foodDraft.value=f?{...clone(f),id:f.source_id?undefined:f.id,name:f.source_id?f.name+' — cópia':f.name}:{name:'',category:'Outros',base_quantity:100,unit:'g',notes:'',...Object.fromEntries(nutrients.map(n=>[n.key,null]))};modal.value='food';}
async function saveFood(){await perform(async()=>{const f=foodDraft.value;await api('foods'+(f.id?'/'+f.id:''),f.id?'PUT':'POST',f);await refresh();modal.value=null;toast('Alimento salvo.');});}
async function deleteFood(f){if(!confirm(`Excluir “${f.name}”?`))return;await perform(async()=>{await api('foods/'+f.id,'DELETE');await refresh();toast('Alimento excluído.');});}
async function saveRecipe(){await perform(async()=>{await api('recipes','POST',recipe.value);await refresh();recipe.value={name:'',ingredients:[],instructions:''};toast('Receita salva e disponível no catálogo de alimentos.');});}
function loadRecipe(r){if(recipe.value.ingredients.length&&!confirm('Substituir os ingredientes atuais?'))return;recipe.value={name:r.name+' — variação',ingredients:clone(r.ingredients),instructions:r.instructions||''};}
function removeMeal(i){if(confirm('Remover esta refeição e seus alimentos?'))plan.value.data.meals.splice(i,1);}
function downloadCSV(){
  const lines=[['Plano',plan.value.data.profile.name],['Paciente',plan.value.data.profile.name],[],['Refeição','Horário','Alimento','Quantidade por unidade','Unidades','Quantidade total','Unidade de medida',...nutrients.map(n=>n.label+' ('+n.unit+')'),'Fonte']];
  for(const meal of plan.value.data.meals)for(const i of meal.items){const f=map.value.get(i.food_id);lines.push([meal.name,meal.time,f.name,`${i.quantity} ${i.measure||'base original'}${i.measure==='goblet'?' ('+(i.measure_ml??150)+' mL)':''}`,i.multiplier??1,consumedQuantity(i,f),f.unit,...nutrients.map(n=>f[n.key]==null?'Não informado':f[n.key]*consumedQuantity(i,f)/f.base_quantity),sourceName(f.source_id)]);}
  lines.push([],['Totais','','','','','','',...nutrients.map(n=>`${summary.value.missing[n.key]?'Parcial: ':''}${summary.value.totals[n.key]}`)],['Observações',plan.value.data.notes]);
  const safe=v=>{const s=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';};
  const url=URL.createObjectURL(new Blob(['\ufeff'+lines.map(l=>l.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='plano-alimentar.csv';a.click();URL.revokeObjectURL(url);
}
async function printPlan(){page.value='plan';await nextTick();window.print();}
function sourceName(id){return db.value.sources.find(s=>s.id===id)?.name||'Cadastro próprio';}
onMounted(async()=>{await perform(async()=>{await refresh();if(db.value.plans.length)selectPlan(db.value.plans[0].id);else{plan.value=clone(db.value.template);saved.value=JSON.stringify(plan.value);page.value='patients';}});loading.value=false;});
</script>

<template>
<div class="app-shell">
  <aside ref="sidebar" id="main-navigation" class="sidebar" :class="{expanded:mobileNav}"><a class="brand" href="#" @click.prevent="page='plan'"><img class="brand-logo" :src="nutriaLogo" alt="" aria-hidden="true"/>nutria<span class="brand-dot">.</span></a><span class="workspace-label">ESPAÇO DE NUTRIÇÃO</span><nav><button v-for="n in nav" :key="n.id" :class="{active:page===n.id}" @click="page=n.id;mobileNav=false"><component :is="n.icon" :size="20"/><span>{{n.name}}</span><ChevronRight v-if="page===n.id" :size="16" class="nav-arrow"/></button></nav><div class="sidebar-bottom"><span class="source-dot"></span> Dados persistidos com segurança<small>Seu planejamento, em um só lugar.</small></div></aside>
  <div class="main-shell"><header class="topbar"><button ref="menuToggle" :aria-expanded="mobileNav" aria-controls="main-navigation" class="icon-button mobile-menu" @click="mobileNav=!mobileNav" aria-label="Abrir navegação"><Menu/></button><span class="breadcrumb">Workspace <ChevronRight :size="14"/> <strong>{{nav.find(n=>n.id===page)?.name}}</strong></span><span class="topbar-right"><span class="local-label"><i></i> Ambiente local</span><span class="local-label">{{db.user?.name}}</span><button class="text-button" @click="logout">Sair</button></span></header>
  <main>
    <div class="error-banner" v-if="error" role="alert"><CircleAlert :size="20"/><span>{{error}}</span><button @click="error=''" aria-label="Dispensar erro"><X :size="18"/></button></div>
    <div v-if="loading" class="loading-state"><LoaderCircle class="spin"/> Carregando seu espaço de nutrição…</div>
    <template v-else-if="plan">
      <div class="page-heading"><div><p class="eyebrow">NUTRIÇÃO COM PROPÓSITO</p><h1>{{nav.find(n=>n.id===page)?.name}}</h1><p class="muted">{{({patients:'Pacientes e informações do seu consultório.',plan:'Organize as refeições e acompanhe o equilíbrio do dia.',profile:'Dados pessoais e objetivos que orientam o planejamento.',foods:'Composição nutricional com a origem de cada informação.',recipes:'Combine ingredientes e calcule sua própria receita.',report:'Uma visão completa da composição do plano.',sources:'Consulte a procedência dos alimentos e as referências da planilha.'})[page]}}</p></div><div class="heading-actions" v-if="page==='plan'||page==='profile'"><button class="button secondary" @click="printPlan"><Printer :size="17"/> Imprimir</button><button class="button primary" :disabled="busy" @click="savePlan"><Save :size="17"/>{{busy?'Salvando…':'Salvar plano'}}</button></div><button v-if="page==='foods'" class="button primary" @click="newFood()"><Plus :size="18"/> Novo alimento</button></div>

      <div class="plan-toolbar" v-if="['plan','profile','report'].includes(page)"><label>Plano <select :value="plan.id||''" @change="selectPlan($event.target.value)"><option v-if="!plan.id" value="">Novo plano (não salvo)</option><option v-for="p in db.plans" :key="p.id" :value="p.id">{{p.data.profile.name}} · #{{p.id}}</option></select></label><span :class="['save-state',{unsaved:dirty}]"><span v-if="dirty">● Alterações não salvas</span><span v-else><Check :size="14"/> Salvo no banco</span></span><button class="text-button" @click="newPlan()"><Plus :size="16"/> Novo plano</button><button class="icon-button" @click="newPlan(true)" aria-label="Duplicar plano" title="Duplicar plano"><Copy :size="17"/></button></div>

      <PatientsPage v-if="page==='patients'" :patients="db.patients" :reload-patients="refresh" @plan="patientPlan"/><template v-if="page==='plan'">
        <div class="patient-strip"><span class="patient-avatar"><UserRound :size="25"/></span><div class="patient-name"><strong>{{plan.data.profile.name||'Paciente sem nome'}}</strong><span>{{plan.data.profile.age}} anos <b>·</b> {{plan.data.profile.sex}} <b>·</b> {{plan.data.profile.goal}}</span></div><div class="patient-measure"><small>PESO</small><strong>{{format(plan.data.profile.weight)}} <span>kg</span></strong></div><div class="patient-measure"><small>ALTURA</small><strong>{{format(plan.data.profile.height,0)}} <span>cm</span></strong></div><button class="text-button" @click="page='profile'">Editar avaliação <ArrowUpRight :size="16"/></button></div>
        <div class="overview-grid"><section class="energy-card"><span class="card-kicker">ENERGIA DO PLANO</span><div class="energy-value">{{summary.missing.calories?'≥ ':''}}{{format(summary.totals.calories,0)}} <span>kcal</span></div><div class="energy-target">de {{format(calculation?.target,0)}} kcal planejadas <span>{{format(pct,0)}}%</span></div><div class="energy-track"><i :style="{width:Math.min(100,Math.max(0,pct||0))+'%'}"></i></div><small v-if="calculation?.target">{{format(Math.abs(calculation.target-summary.totals.calories),0)}} kcal {{calculation.target>=summary.totals.calories?'disponíveis no planejamento':'acima da meta'}}</small></section><section class="nutrient-card" v-for="n in nutrients.slice(1,4)" :key="n.key"><span class="nutrient-label"><i :style="{background:n.color}"></i>{{n.label}}</span><strong>{{summary.missing[n.key]?'≥ ':''}}{{format(summary.totals[n.key])}} <span>g</span></strong><div class="subtle-track"><i :style="{background:n.color,width:macroPercent[nutrients.indexOf(n)-1]+'%'}"></i></div><small>{{format(macroPercent[nutrients.indexOf(n)-1],0)}}% da energia dos macros</small></section></div>
        <div class="planning-grid"><div><div class="section-head"><h2>Refeições do dia <span class="count-badge">{{plan.data.meals.length}}</span></h2><button class="text-button" @click="plan.data.meals.push({name:'Lanche - Tarde',time:'16:00',items:[]})"><Plus :size="16"/> Refeição</button></div><MealCard v-for="(meal,i) in plan.data.meals" :key="i" :meal="meal" :index="i" :foods="map" :types="db.meal_types" @add="openPicker(i)" @remove="removeMeal(i)"/><section class="panel notes"><h2>Observações do plano</h2><textarea v-model="plan.data.notes" placeholder="Orientações, substituições e observações…" rows="4" aria-label="Observações do plano"></textarea></section></div><aside class="daily-summary"><section class="panel"><div class="section-head"><h2>Equilíbrio do dia</h2><ChartNoAxesCombined :size="19"/></div><div class="donut" :style="{background:donut}" role="img" :aria-label="`Distribuição energética: proteínas ${format(macroPercent[0])}%, carboidratos ${format(macroPercent[1])}%, gorduras ${format(macroPercent[2])}%`"><div><strong>{{format(summary.totals.calories,0)}}</strong><span>kcal no plano</span></div></div><div class="legend-row" v-for="(n,i) in nutrients.slice(1,4)" :key="n.key"><span><i :style="{background:n.color}"></i>{{n.label}}</span><b>{{format(macroPercent[i],0)}}%</b></div><div class="summary-divider"></div><div class="legend-row" v-for="n in nutrients.slice(4)" :key="n.key"><span>{{n.label}}</span><b>{{summary.missing[n.key]?'≥ ':''}}{{format(summary.totals[n.key])}} {{n.unit}}</b></div><p class="footnote">Distribuição calculada com 4 kcal/g de proteínas e carboidratos e 9 kcal/g de gorduras.</p><p class="data-note" v-if="Object.values(summary.missing).some(Boolean)">Há nutrientes não informados. “≥” indica soma parcial dos valores conhecidos.</p><button class="button secondary full" @click="page='report'">Ver análise completa <ArrowUpRight :size="16"/></button></section><section class="reference-card"><Database :size="20"/><h3>Informação com origem</h3><p>{{db.foods.length.toLocaleString('pt-BR')}} registros para consultar, com dados da sua planilha, da TACO e do IBGE.</p><button class="text-button" @click="page='sources'">Conhecer as fontes <ArrowUpRight :size="16"/></button></section></aside></div>
      </template>

      <template v-if="page==='profile'"><div class="profile-grid"><form class="panel form-panel" @submit.prevent="savePlan"><h2>Paciente e planejamento</h2><label>Vincular ao paciente<select v-model="plan.patient_id" @change="selectPatient"><option :value="null">Sem vínculo</option><option v-for="p in db.patients" :value="p.id" :key="p.id">{{p.name}}</option></select></label><div class="form-grid"><label class="span-2">Nome do paciente<input v-model="plan.data.profile.name" required maxlength="160"/></label><label>Sexo<select v-model="plan.data.profile.sex"><option>Feminino</option><option>Masculino</option></select></label><label>Idade (anos)<input v-model.number="plan.data.profile.age" type="number" min="1" max="120" required/></label><label>Peso (kg)<input v-model.number="plan.data.profile.weight" type="number" min="0.1" max="500" step="0.1" required/></label><label>Altura (cm)<input v-model.number="plan.data.profile.height" type="number" min="1" max="300" step="0.1" required/></label><label class="span-2">Atividade física<select v-model="plan.data.profile.activity"><option v-for="a in db.activities" :key="a.name">{{a.name}}</option></select><small>{{db.activities.find(a=>a.name===plan.data.profile.activity)?.description}}</small></label><label>Objetivo<select v-model="plan.data.profile.goal"><option>Perder Peso</option><option>Manter o Peso</option><option>Ganhar Peso</option></select></label><label>Ajuste calórico (kcal)<input v-model.number="plan.data.profile.adjustment" type="number" min="0" max="10000" :disabled="plan.data.profile.goal==='Manter o Peso'" placeholder="Sem ajuste"/><small>Deixe vazio para usar o gasto energético total.</small></label></div><button class="button primary" :disabled="busy"><Save :size="17"/> Salvar avaliação</button></form><div><section class="panel assessment"><h2>Resultados da avaliação</h2><div class="assessment-main"><span>IMC</span><strong>{{format(calculation?.bmi)}}</strong><small>kg/m²</small></div><span class="pill">{{calculation?.bmi_label}}</span><p class="footnote">Classificação original da planilha de 2019, com faixas diferentes por sexo.</p><div class="result-row"><span>Metabolismo basal</span><b>{{format(calculation?.bmr,0)}} kcal</b></div><div class="result-row"><span>Gasto energético total</span><b>{{format(calculation?.energy,0)}} kcal</b></div><div class="result-row highlight"><span>Meta diária</span><b>{{format(calculation?.target,0)}} kcal</b></div><p class="footnote">Método Harris-Benedict com os coeficientes usados na planilha. Ajuste aplicado conforme o objetivo.</p><p v-if="calculation?.target<=0" class="data-note">Reduza o ajuste para obter uma meta positiva.</p></section><button v-if="plan.id" class="text-button danger delete-plan" @click="removePlan"><Trash2 :size="16"/> Excluir este plano</button></div></div></template>

      <template v-if="page==='foods'"><div class="catalog-stats"><span><b>{{db.foods.length.toLocaleString('pt-BR')}}</b> registros no catálogo</span><span><b>{{db.foods.filter(f=>f.source_id===11).length}}</b> da planilha original</span><span><b>{{db.foods.filter(f=>f.source_id===3).length}}</b> da TACO oficial</span><span><b>{{db.foods.filter(f=>f.source_id===12).length}}</b> do IBGE / POF</span></div><section class="panel catalog"><div class="catalog-filters"><label class="search"><Search :size="18"/><input v-model="search" placeholder="Buscar no catálogo de alimentos" aria-label="Buscar no catálogo"/></label><select v-model="foodCategory" aria-label="Filtrar categoria"><option value="">Todas as categorias</option><option v-for="c in db.categories" :key="c" :value="c">{{label(c)}}</option></select><select v-model="foodSource" aria-label="Filtrar fonte"><option value="">Todas as fontes</option><option v-for="s in db.sources.filter(s=>s.imported_count)" :key="s.id" :value="String(s.id)">{{s.name}}</option><option value="custom">Cadastros próprios e receitas</option></select></div><div class="table-scroll"><table><thead><tr><th>Alimento</th><th>Base</th><th v-for="n in nutrients" :key="n.key">{{n.label}}<small>{{n.unit}}</small></th><th>Ações</th></tr></thead><tbody><tr v-for="f in filteredFoods.slice((foodPage-1)*25,foodPage*25)" :key="f.id"><td><strong>{{f.name}}</strong><small>{{label(f.category)}}</small><span class="source-tag" :class="{taco:f.source_id===3}">{{sourceName(f.source_id)}}</span><details v-if="f.notes||f.source_row"><summary>Origem e observações</summary><p>{{f.notes}}</p><p v-if="f.source_row">Linha {{f.source_row}} da fonte. Código {{f.source_key}}.</p></details></td><td>{{format(f.base_quantity)}}<small>{{f.unit}}</small></td><td v-for="n in nutrients" :key="n.key">{{f[n.key]==null?(f.raw_values?.[n.key]||'—'):format(f[n.key])}}</td><td><button class="icon-button" @click="newFood(f)" :aria-label="f.source_id?'Duplicar alimento':'Editar alimento'" :title="f.source_id?'Duplicar e editar':'Editar'"><Copy :size="16"/></button><button v-if="!f.source_id&&!db.recipes.some(r=>r.food_id===f.id)" class="icon-button danger" @click="deleteFood(f)" aria-label="Excluir alimento"><Trash2 :size="16"/></button></td></tr></tbody></table></div><p v-if="!filteredFoods.length" class="empty">Nenhum alimento corresponde aos filtros.</p><footer class="pagination"><span>{{filteredFoods.length}} resultados · Página {{foodPage}} de {{foodPages}}</span><div><button class="button secondary" :disabled="foodPage===1" @click="foodPage--">Anterior</button><button class="button secondary" :disabled="foodPage>=foodPages" @click="foodPage++">Próxima</button></div></footer></section><p class="footnote">Tr = traço · NA = não aplicável · — = não informado. Alimentos com o mesmo nome e preparo são consolidados, priorizando a TACO oficial.</p></template>

      <template v-if="page==='recipes'"><div class="profile-grid"><section class="panel form-panel"><div class="section-head"><h2>Calculadora de receita</h2><BookOpen :size="20"/></div><label>Nome da receita<input v-model="recipe.name" placeholder="Ex.: Panqueca de aveia" maxlength="200"/></label><div class="recipe-ingredients"><div class="meal-item" v-for="(i,index) in recipe.ingredients" :key="index"><div class="food-name"><strong>{{map.get(i.food_id)?.name}}</strong><small>{{sourceName(map.get(i.food_id)?.source_id)}}</small></div><PortionInput :item="i" :food="map.get(i.food_id)" /><button class="icon-button" @click="recipe.ingredients.splice(index,1)" aria-label="Remover ingrediente"><X :size="17"/></button></div><p v-if="!recipe.ingredients.length" class="empty">Adicione os ingredientes para calcular a receita.</p></div><button class="button secondary" @click="openPicker('recipe')"><Plus :size="16"/> Adicionar ingrediente</button><label>Modo de preparo e observações<textarea v-model="recipe.instructions" rows="5" placeholder="Descreva o preparo…"></textarea></label><button class="button primary" :disabled="busy||!recipe.name||!recipe.ingredients.length" @click="saveRecipe"><Save :size="17"/> Salvar receita no catálogo</button></section><div><section class="panel"><h2>Composição da receita</h2><div class="recipe-weight"><strong>{{format(recipeSummary.quantity)}}</strong><span>g de ingredientes</span></div><div class="legend-row" v-for="n in nutrients" :key="n.key"><span>{{n.label}}</span><b>{{recipeSummary.missing[n.key]?'≥ ':''}}{{format(recipeSummary.totals[n.key])}} {{n.unit}}</b></div><p class="footnote">A porção padrão corresponde à soma dos ingredientes, como na aba Receita. A perda de água no preparo não é estimada.</p><p v-if="Object.values(recipeSummary.missing).some(Boolean)" class="data-note">Nutrientes incompletos serão salvos como não informados.</p></section><section class="panel saved-recipes"><h2>Receitas salvas <span class="count-badge">{{db.recipes.length}}</span></h2><div v-for="r in db.recipes" :key="r.id" class="saved-recipe"><strong>{{r.name}}</strong><small>{{r.ingredients.length}} ingredientes · {{format(map.get(r.food_id)?.base_quantity)}} g</small><p v-if="r.instructions">{{r.instructions}}</p><button class="text-button" @click="loadRecipe(r)"><Copy :size="15"/> Usar como base</button></div><p v-if="!db.recipes.length" class="muted">Suas receitas aparecerão aqui e na busca de alimentos.</p></section></div></div></template>

      <template v-if="page==='report'"><div class="report-actions"><button class="button secondary" @click="downloadCSV"><Download :size="17"/> Exportar CSV</button><button class="button secondary" @click="printPlan"><Printer :size="17"/> Imprimir plano / PDF</button></div><div class="report-totals"><section class="panel" v-for="n in nutrients" :key="n.key"><span class="nutrient-label"><i :style="{background:n.color}"></i>{{n.label}}</span><strong>{{summary.missing[n.key]?'≥ ':''}}{{format(summary.totals[n.key])}} <small>{{n.unit}}</small></strong></section></div><section class="panel report-chart"><div class="section-head"><h2>Distribuição por refeição</h2><select v-model="chartMetric" aria-label="Nutriente do gráfico"><option v-for="n in nutrients" :key="n.key" :value="n.key">{{n.label}} ({{n.unit}})</option></select></div><div class="bar-row" v-for="(m,i) in plan.data.meals" :key="i"><span>{{m.name}} <small>{{m.time}}</small></span><div class="bar-track"><i :style="{width:(summary.totals[chartMetric]?total(m.items,map).totals[chartMetric]/summary.totals[chartMetric]*100:0)+'%',background:nutrients.find(n=>n.key===chartMetric).color}"></i></div><b>{{total(m.items,map).missing[chartMetric]?'≥ ':''}}{{format(total(m.items,map).totals[chartMetric])}}</b></div></section><section class="panel category-report"><h2>Consumo por categoria</h2><div class="table-scroll"><table><thead><tr><th>Categoria</th><th>Itens</th><th>Massa equivalente (g)</th><th v-for="n in nutrients" :key="n.key">{{n.label}} ({{n.unit}})</th></tr></thead><tbody><tr v-for="g in grouped" :key="g.name"><td>{{label(g.name)}}</td><td>{{g.count}}</td><td>{{format(g.quantity)}}</td><td v-for="n in nutrients" :key="n.key">{{g.missing[n.key]?'≥ ':''}}{{format(g.totals[n.key])}}</td></tr><tr><th>Total</th><th>{{allItems.length}}</th><th>{{format(summary.quantity)}}</th><th v-for="n in nutrients" :key="n.key">{{summary.missing[n.key]?'≥ ':''}}{{format(summary.totals[n.key])}}</th></tr></tbody></table></div></section><p class="footnote">Valores calculados a partir das quantidades do plano. Somas com “≥” são parciais por conterem nutrientes não informados.</p></template>

      <template v-if="page==='sources'"><div class="source-intro"><Database :size="28"/><div><h2>Transparência em cada alimento</h2><p>Os valores originais são preservados. A fonte e a linha de origem acompanham cada registro importado.</p></div></div><div class="sources-grid"><section class="panel source-card" v-for="s in db.sources" :key="s.id"><span class="eyebrow">{{({nutrients:'COMPOSIÇÃO NUTRICIONAL',calculator:'CALCULADORA',recipes:'RECEITAS',workbook:'ARQUIVO ORIGINAL'})[s.kind]}}</span><h2>{{s.name}}</h2><span :class="['source-status',{imported:s.imported_count}]"><Check v-if="s.imported_count" :size="14"/>{{s.imported_count?s.imported_count+' alimentos importados':s.status}}</span><p v-if="s.id===3">TACO, 4ª edição revisada e ampliada, NEPA/Unicamp (2011). Arquivo oficial disponibilizado na página de publicações.</p><p v-if="s.id===12">IBGE, POF 2008–2009, publicação de 2011. Seleção com foco em café da manhã. Valores por 100 g, com a referência original de cada composição nas observações do alimento.</p><p v-if="s.id===11">Alimentos exclusivos da planilha fornecida. As cópias com o mesmo nome na TACO foram consolidadas na fonte oficial.</p><p class="footnote">Referência: {{s.cell}}</p><a v-if="s.url" :href="s.current_url||s.url" target="_blank" rel="noopener noreferrer" class="text-button">Consultar fonte <ArrowUpRight :size="16"/></a><a v-if="s.download_url" :href="s.download_url" target="_blank" rel="noopener noreferrer" class="text-button">Arquivo original <Download :size="15"/></a></section></div><section class="panel methodology"><h2>Medidas das bebidas</h2><p>Bebidas prontas são exibidas por 100 mL. Conversões usam densidades de referência da FAO/INFOODS (2012); aproximações estão identificadas nas observações. Xícara de chá: 200 mL; xícara de café: 50 mL; copo médio: 240 mL (IBGE). A taça começa com 150 mL como convenção editável do aplicativo.</p><p><a href="https://www.fao.org/4/ap815e/ap815e.pdf" target="_blank" rel="noopener noreferrer">Densidades FAO/INFOODS</a> · <a href="https://www.ibge.gov.br/biblioteca/visualizacao/livros/liv50000.pdf" target="_blank" rel="noopener noreferrer">Medidas caseiras IBGE</a></p><h2>Fidelidade à planilha</h2><p>Plano original: versão 4.0, março de 2019, criado por William Alves dos Santos. As nove refeições, os horários e os 15 itens preenchidos foram importados. A quantidade de ovo registrada como 1 foi mantida como 1 g, conforme a fórmula original.</p><p>IMC, Harris-Benedict, fatores de atividade, ajuste calórico e cálculo proporcional de nutrientes reproduzem as fórmulas da planilha. O ajuste vazio usa o gasto energético total. Totais não dependem do preenchimento da primeira linha da refeição.</p><p>As fontes de receitas e calculadoras permanecem como referências de consulta. Não há sincronização automática com sites externos. Valores de nutrientes ausentes são identificados; não são convertidos em zero.</p></section></template>
    </template>
    <div v-else-if="!loading" class="panel"><p>Não foi possível carregar os dados.</p><button class="button primary" @click="reload">Tentar novamente</button></div>
    <footer class="app-footer"><span>nutria. <span>Planejamento alimentar</span></span><span>Feito para acompanhar o seu cuidado.</span></footer>
  </main></div>
  <div class="toast" v-if="notice" role="status"><Check :size="18"/>{{notice}}</div>
  <dialog ref="dialog" @cancel="modal=null" @close="modal=null" :aria-label="modal==='picker'?'Adicionar alimento':'Cadastro de alimento'"><FoodPicker v-if="modal==='picker'" :foods="db.foods" :sources="db.sources" @add="addFood" @close="modal=null"/><form v-if="modal==='food'" class="food-form" @submit.prevent="saveFood"><div class="section-head"><h2>{{foodDraft.id?'Editar alimento':'Novo alimento'}}</h2><button type="button" class="icon-button" @click="modal=null" aria-label="Fechar"><X/></button></div><p class="data-note" v-if="error">{{error}}</p><div class="form-grid"><label class="span-2">Descrição<input v-model="foodDraft.name" required maxlength="200"/></label><label>Categoria<input v-model="foodDraft.category" list="categories" required/><datalist id="categories"><option v-for="c in db.categories" :key="c" :value="c">{{label(c)}}</option></datalist></label><label>Unidade<select v-model="foodDraft.unit"><option>g</option><option>mL</option><option>g/mL</option></select></label><label class="span-2">Quantidade padrão<input type="number" v-model.number="foodDraft.base_quantity" min="0.1" max="100000" step="any" required/></label><label v-for="n in nutrients" :key="n.key">{{n.label}} ({{n.unit}})<input type="number" v-model.number="foodDraft[n.key]" min="0" max="1000000" step="any" placeholder="Não informado"/></label><label class="span-2">Observações / fonte<textarea v-model="foodDraft.notes" rows="3"></textarea></label></div><button class="button primary" :disabled="busy">Salvar alimento</button></form></dialog>
</div>
</template>
